server:
  port: 9090

spring:
  application:
    name: EtiqaChatbot
  profiles:
    active: dev
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
      # 发送的对象信息变为json格式
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
  topic:
    chat-topic1: CHAT_HISTORY
    chat-topic2: RESPONSE_HISTORY